spring.application.name=audit-compliance-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_platform
spring.datasource.username=postgres
spring.datasource.password=ravi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=myverysecuresecretkeymyverysecuresecretkey